levys19/Cracking_the_resume

- Pages/formpage.html
- Pages/homepage.html
- Pages/styles/formpage.css
> Added more input fields

- README.md
Updated Readme file to include instructions to how to install the web app 
#31
> Updated Readme file 

- README.md
> Upadted Readme again

- README.md
- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/resumeViewing.ejs
- cracking_the_resume/views/settings.ejs
#38 
Fixed Readme
Changed the accounts button to settings button to make it less 
confusing
> routing-srav1

- Minutes/Minutes_2:23 .txt
> Meeting Minutes upload 2/23

- cracking_the_resume/Models/user.js
- cracking_the_resume/package-lock.json
- cracking_the_resume/package.json
- cracking_the_resume/routes/split.js
- cracking_the_resume/seeds.js
> Ecrypting user password

- Minutes/Minutes 3:16:18.txt
> Meeting Minutes

- package-lock.json
got rid of the crackingtheresume folder
> got rid of that

- cracking_the_resume/routes/accounts.js
- cracking_the_resume/routes/resumeViewing.js
- cracking_the_resume/routes/settings.js
- cracking_the_resume/routes/signup.js
- cracking_the_resume/routes/split.js
#82 
Allow users to have access to all the pages
> Allowed user access to all the pages.

- cracking_the_resume/app.js
- cracking_the_resume/package-lock.json
- cracking_the_resume/routes/accounts.js
- cracking_the_resume/routes/redirect.js
- cracking_the_resume/routes/resumeViewing.js
- cracking_the_resume/routes/settings.js
- cracking_the_resume/routes/signup.js
- cracking_the_resume/routes/split.js
- cracking_the_resume/seeds.js
- cracking_the_resume/views/signUp.ejs
#85 
Fixed the routing issues.
There should be no error in develop
> Fixed all the routing problems with the pages.

- cracking_the_resume/routes/redirect.js
> changed filename of resumes from .pdf to .png

- cracking_the_resume/public/Javascript/viewing.js
- cracking_the_resume/views/resumeViewing.ejs
- cracking_the_resume/views/signUp.ejs
fixed duplicates for resumeviewing page #67
> fixed duplicates

- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/resumeViewing.ejs
- cracking_the_resume/views/signUp.ejs
> simplified comments

- cracking_the_resume/routes/redirect.js
- cracking_the_resume/routes/settings.js
- cracking_the_resume/views/settings.ejs
Added post request to the settings page
#115
> Fixed settings page 

- cracking_the_resume/Models/user.js
- cracking_the_resume/views/resumeViewing.ejs
#141 
Fixed the logout button using the hot-fix protocol.
> logout button fixed and deleted console log statements.

- cracking_the_resume/public/stylesheets/viewing.css
- cracking_the_resume/views/resumeViewing.ejs
> new layout for viewing page

- cracking_the_resume/public/Javascript/signup.js
- cracking_the_resume/views/signUp.ejs
> png bug fix

- cracking_the_resume/public/stylesheets/homepage.css
- cracking_the_resume/views/signUp.ejs
> Removed terms

- cracking_the_resume/public/stylesheets/homepage.css
- cracking_the_resume/views/homePage.ejs
> fixed image sizing for issue #145

- cracking_the_resume/public/stylesheets/homepage.css
- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/homePage.ejs
> Fixed homepage picture

- cracking_the_resume/public/Javascript/signup.js
- cracking_the_resume/views/signUp.ejs
> Png restriction fix and pathing fix

- cracking_the_resume/views/resumeViewing.ejs
> image layout for resumeviewing page

- cracking_the_resume/logIn/index.js
- cracking_the_resume/routes/accounts.js
- cracking_the_resume/routes/individual.js
- cracking_the_resume/routes/redirect.js
- cracking_the_resume/routes/resumeViewing.js
- cracking_the_resume/routes/settings.js
- cracking_the_resume/routes/split.js
- cracking_the_resume/views/redirect.ejs
- cracking_the_resume/views/resumeViewing.ejs
Made it so that users don't have access to the resumeViewing Page, and also a user's own resume is not displayed on the resumeViewing page. 
#180 
#188
> Made it so that users don't have access to the resumeViewing Page, and user resume not displayed

- cracking_the_resume/public/Javascript/account.js
- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/individual.ejs
> Beta empty commet/word limit

- cracking_the_resume/app.js
- cracking_the_resume/logIn/index.js
- cracking_the_resume/routes/accounts.js
- cracking_the_resume/routes/individual.js
- cracking_the_resume/routes/resumeViewing.js
- cracking_the_resume/routes/settings.js
- cracking_the_resume/routes/split.js
- cracking_the_resume/views/resumeViewing.ejs
Users need to have access to go to certain pages 
User's own resume is not displayed on the resumeViewing page with isLoggedIn
#187 
#188
> Users have to log in to access certain pages, and user's own resume doesn't display on the resume Viewing Page

- cracking_the_resume/package.json
- cracking_the_resume/public/Javascript/sign.js
- cracking_the_resume/routes/redirect.js
- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/settings.ejs
changed the package.json so it works properly and launch
> minor changes

- cracking_the_resume/views/signUp.ejs
> changed from png to pdf

- cracking_the_resume/public/stylesheets/acc.css
I changed acc.css file
Line 147
change from: overflow: hidden;
to: overflow-wrap: break-word;
> collab assignment comment wrapping

- cracking_the_resume/app.js
- cracking_the_resume/public/Javascript/account.js
- cracking_the_resume/views/account.ejs
- cracking_the_resume/views/individual.ejs
> Votes functionality

- cracking_the_resume/views/account.ejs
> Updated account.ejs
